code/stratos/quizapplication/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quizes.urls',namespace="quizes")),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

code/stratos/quizes/urls.py
from django.urls import path
from .views import (
    QuizListView,
    quiz_view,
    quiz_data_view,
    save_quiz_view,
    add_quiz,
    add_save,
    remove_save
)

app_name = 'quizes'

urlpatterns = [
    path('',QuizListView.as_view(),name='main-view'),
    path('remove',remove_save,name="remove-view"),
    path('add/',add_quiz,name='add-quiz'),
    path('add/save',add_save,name='add-save'),
    path('<pk>/',quiz_view,name='quiz-view'),
    path('<pk>/data',quiz_data_view,name="quiz-data-view"),
    path('<pk>/save',save_quiz_view,name="save-view"),
    

]

code/stratos/quizes/models.py
from django.db import models
import random

DIFF_CHOICES = (   
    ('easy','easy'),
    ('medium','medium'),
    ('hard','hard'),
)
# Create your models here.
class Quiz(models.Model):
    name = models.CharField(max_length=120)
    topic = models.CharField(max_length=120)
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="Duration of the quiz")
    required_score_to_pass = models.IntegerField(help_text="required score in percent")
    difficulty = models.CharField(max_length=6,choices=DIFF_CHOICES)

    class Meta:
        verbose_name_plural = 'Quizes'

    def __str__(self):
        return f"{self.name}-{self.topic}"

    def get_question(self):
        que = list(self.question_set.all())
        print(que)
        random.shuffle(que)
        return que[:self.number_of_questions] 

code/stratos/quizes/views.py
from urllib import response
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse,HttpResponse
from questions.models import Answer, Question
from results.models import Result
from django.shortcuts import redirect
from .memento import Memento,Originator,Caretaker
from django.views.decorators.csrf import csrf_exempt, csrf_protect
import requests

# Create your views here.

default_categories = {}

temp_categories = ["General Knowledge",
"Books","Film","Music","Musicals & Theatres",
"Television","Video Games","Board Games",
"Science & Nature","Science Computers",
"Science Mathematics","Mythology","Sports",
"Geograpy","History","Politics",
"Art","Celebrities","Animals",
"Vehicles","Comics","Gadgets",
"Japanese","Cartoon & Animations"
]

for index,value in enumerate(temp_categories):
    default_categories[index+9]=value


class QuizListView(ListView):
    model = Quiz
    template_name = 'quizes/main.html'
    


def add_quiz(request):
    request.log.info("Adding the quiz")
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        temp = request.POST
        parameters = {
            "amount":int(temp['amount']),
            "category":int(temp['choice']),
            "difficulty":temp['difficulty'],
            "type":temp['type']
        }
        data = requests.get("https://opentdb.com/api.php",params=parameters).json()["results"]
        
        return JsonResponse({
            'data':data,
        })
    else:    
        return render(request,"quizes/add_quiz.html",context={"choices":default_categories})

@login_required
def add_save(request):
    request.log.info("Saving the quiz")
    data = request.POST
    data_ = dict(data.lists())
    obj = Originator(data_)
    obj.adding_quiz()
    
    return JsonResponse({"Objective":"Achieved"})


@login_required
def remove_save(request):
    request.log.info("Removing the quiz")
    print("Entered the remove state")
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        data = request.POST
        obj2 = Caretaker()
        obj = Memento(data)
        obj.rem()
        
    return JsonResponse({"Objective":"Achieved and Removed "})


@login_required
def quiz_view(request,pk):
    request.log.info("Getting the quiz")
    quiz = Quiz.objects.get(pk=pk)
    return render(request,'quizes/quiz.html',{'obj':quiz})

@login_required
def quiz_data_view(request,pk):
    request.log.info("Storing the questions and answers")
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for q in quiz.get_question():
        answers = []
        for a in q.get_answer():
            answers.append(a.text)
        questions.append({str(q):answers})
    
    return JsonResponse({
        'data':questions,
        'time':quiz.time,
    })

@login_required
def save_quiz_view(request,pk):
    request.log.info("Saving the quiz result")
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        questions = []
        data = request.POST
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')
        print(data_)

        for k in data_.keys():
            question = Question.objects.get(text=k)
            print(question)
            questions.append(question)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)
        score = 0
        multiplier = 100 / quiz.number_of_questions
        results = []
        correct_answer = None

        for q in questions:
            a_selected = request.POST.get(q.text)
            print('a_select',a_selected)
            if a_selected != "":
                question_answer = Answer.objects.filter(question=q)
                
                for a in question_answer:
                    if a_selected == a.text:
                        
                        if a.correct:
                            score +=1
                            correct_answer = a.text
                    else:
                        if a.correct:
                            correct_answer = a.text
                
                results.append({str(q):{'correct_answer':correct_answer,'answered':a_selected}})
            else:
                results.append({str(q):'not answered'})

        score_ = score * multiplier 
        Result.objects.create(quiz=quiz,user=user,score=score_)
        if score_ >= quiz.required_score_to_pass:
            return JsonResponse({'passed':True,'score':score_,'results':results})
        else:
            return JsonResponse({'passed':False,'score':score_,'results':results})

code/stratos/quizes/templates/quizes/add_quiz.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
<script src="{% static 'quizes/add_quiz.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
add_quiz
{% endblock title %}

{% block content %}

<form action="" method="post" id="addForm">
    {% csrf_token %}

    <label for="num_of_question" class="form-label">Number of Questions</label>
    <input type="number" name="num_of_question" class="form-control" id="num_of_question" required>
    <label for="difficulty" class="form-label">Difficulty</label>
    <select name="difficulty" id="difficult" class="form-control">
        <option value="easy">Easy</option>
        <option value="medium">Medium</option>
        <option value="hard">Difficult</option>
    </select>
    <label for="choices" class="form-label">Choices</label>
    <div class="dropdown" class="form-select ">
        <select name="cho" id="cho" class="form-control">
            {% for key,value in choices.items %}
            <option value="{{key}}" name="{{key}}">{{value}}</option>
            {% endfor %}
        </select>

    </div>
    <input type="submit" name="submit" id="submit" value="submit" class="btn btn-success"
        style="margin-top: 30px; width: 100%;">
</form>
<div id="que-ans"></div>

<form id="quiz-form" action="" class="mt-3 mb-3" class="not-visible">
    {% csrf_token %}
    <label for="nameofquiz" required class="goibibo not-visible form-label">Name of the quiz</label>
    <input type="text" name="nameofquiz" required class="goinp goibibo not-visible form-control">
    <label for="topic" required class="goibibo not-visible form-label">Topic</label>
    <input type="text" name="topic" required class=" goinp goibibo not-visible form-control">
    <label for="numberofquestion" required class="goibibo not-visible form-label">Number of question</label>
    <input type="text" required class="goinp goibibo not-visible form-control" name="numberofquestion">
    <label for="time" required class="goibibo not-visible form-label">Time</label>
    <input type="text" required class=" goinp goibibo not-visible form-control" name="time">
    <label for="reqscoretopass" required class="goibibo not-visible form-label">Required score to pass</label>
    <input type="text" required class=" goinp goibibo not-visible form-control" name="reqscoretopass">
    <label for="difficulty" required class="goibibo not-visible form-label">Difficulty</label>
    <select name="difficulty" required class="goinp goibibo not-visible form-control" id="">
        <option value="easy">Easy</option>
        <option value="medium">Medium</option>
        <option value="difficult">Difficult</option>
    </select>


    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add New Question-4th option should be right</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="post" id="modal-form">
                        <label for="addquestion">Add Question</label>
                        <input type="text" id="addquestion">
                        <br><br>
                        <label for="op1">Option 1</label>&nbsp;&nbsp;&nbsp;<input type="text" id="op1" class="op">
                        <br><br><br>
                        <label for="op2">Option 2</label>&nbsp;&nbsp;&nbsp;<input type="text" id="op2" class="op">
                        <br><br><br>
                        <label for="op3">Option 3</label>&nbsp;&nbsp;&nbsp;<input type="text" id="op3" class="op">
                        <br><br><br>
                        <label for="op4">Option 4</label>&nbsp;&nbsp;&nbsp;<input type="text" id="op4" class="opcor">
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="save-modal-form" data-bs-dismiss="modal">Save changes</button>
                </div>
            </div>
        </div>
    </div>
    <div id="quiz-box"></div>
    <button type="button" class="btn btn-warning not-visible" id="modbtn" data-bs-toggle="modal"
        data-bs-target="#exampleModal" style="width: 100%;">
        Add custom question &spades;
    </button>
    <br>

    <br>
    <input type="submit"  value="save" class="btn form-label btn-primary mt-3 goibibo not-visible" id="savebtn"></input>

</form>


{% endblock content %}

code/stratos/quizes/templates/quizes/main.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
<script src="{% static 'quizes/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}

  <!-- Modal -->
  <div class="modal fade" id="quizstartmodal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Start ?</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body" id="modal-body-confirm">
          
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-bs-dismiss="modal">no</button>
          <button type="button" id="start-button" class="btn btn-success">yes</button>
        </div>
      </div>
    </div>
  </div>

  <div class="h1">
      Quiz List
  </div>
  <hr>
  {% for obj in object_list %}

    <button
      class="btn btn-link modal-button"
      data-pk = "{{obj.pk}}"
      data-quiz = "{{obj.name}}"
      data-questions = "{{obj.number_of_questions}}"
      data-difficulty = "{{obj.difficulty}}"
      data-time = "{{obj.time}}"
      data-pass = "{{obj.required_score_to_pass}}"
      data-bs-toggle="modal"
      data-bs-target="#quizstartmodal"
    >
    {{obj.name}}
    </button><br>
    <button
    data-pk = "{{obj.pk}}"
    data-quiz = "{{obj.name}}"
    style="align-items: flex-end;" 
    class="btn btn-link remove-button" 
    id="removeBtn"
    >
    Remove
  </button>

  {% endfor%}

{% if user.is_superuser %}
<a href="{% url 'quizes:add-quiz' %}" class="btn btn-primary">Add quiz</a>
<a href="" class="btn btn-primary">Undo</a>
{% endif %}

{% endblock content %}

code/stratos/quizes/templates/quizes/quiz.html
{% extends 'base.html' %}
{% load static %}
{% block scripts %}
<script src="{% static 'quizes/quiz.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}


{% block content %}
<div class="row">
    <div class="col">
        <b>{{obj.name}}</b>
        <p>Score to pass {{obj.required_score_to_pass}}%</p>
    </div>
    <div class="col text-right" id="timer-box"></div>
</div>

<a href="{% url 'quizes:main-view'%}" class="btn btn-danger">Go back</a>

<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    
    <div id="quiz-box"></div>
    <button type="submit" class="btn btn-primary mt-3">save</button>

</form>

<div id="score-box"></div>
<div id="result-box"></div>
{% endblock content %}